# Generated by Django 3.1.7 on 2021-03-14 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_lended', models.DateField(auto_now_add=True, verbose_name='Data do Emprestimo')),
                ('return_estimate', models.DateField(verbose_name='Retorno Estimado')),
                ('return_date', models.DateField(null=True, verbose_name='Data do retorno')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('id_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lended_book', to='book.book')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_lended', to='client.client', verbose_name='Cliente')),
            ],
        ),
    ]
