# Generated by Django 3.1.7 on 2021-03-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('author', models.CharField(max_length=200, verbose_name='Autor')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('emprestado', 'Emprestado')], default='disponivel', max_length=30, verbose_name='Situação')),
            ],
        ),
    ]
